version: "3.8"
services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbit
    environment:
      - RABBITMQ_DEFAULT_USER=amqpuser
      - RABBITMQ_DEFAULT_PASS=ai_epilepsy10*
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      AIEp-net:
        ipv4_address: 172.16.238.13
  ftp: 
    image: delfer/alpine-ftp-server
    container_name: ftp
    environment:
      USERS: "ftpuser|ai_epilepsy10*|/home/user"
    ports:
      - "5021:21"
      - "21000-21010:21000-21010"
    networks:
      AIEp-net:
        ipv4_address: 172.16.238.12
  sql:
    image: mysql:8.0
    container_name: sql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "ai_epilepsy10*"
    ports:
      - "3306:3306"
    networks:
      AIEp-net:
        ipv4_address: 172.16.238.10
    volumes:
      - .docker/setup.sql:/docker-entrypoint-initdb.d/setup.sql
      - db_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD-SHELL", "mysql -h localhost -P 3306 -u root -p$$MYSQL_ROOT_PASSWORD -e 'SELECT 1;'" ]
      interval: 2s
      timeout: 5s
      retries: 10
networks:
  AIEp-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.238.0/16
volumes:
  db_data: