version: "1"
services:
  epilepsy-backend:
    build: Server/
    ports:
      - "4301:3000"

  epilepsy-frontend:
    build: front-end/
    ports:
      - "4300:4000"
  epilepsy-mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Pipemerca410*
      MYSQL_DATABASE: Ai-Epilepsy
networks:
  epilepsy-net: